package program.entity.enums;

public enum EnumRole {
    RECEPTIONIST,
    CASHIER,

    GLOBAL_INVENTORY_MANAGER,
    BRANCH_INVENTORY_MANAGER,

    GLOBAL_HUMAN_RESOURCE_MANAGER,
    BRANCH_HUMAN_RESOURCE_MANAGER,

    BRANCH_ADMIN,
    SUPER_ADMIN
}
